In [53]:
# 分析basket 电影分类中的频繁项集和关联规则
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# 数据加载
market = pd.read_csv('./Market_Basket_Optimisation.csv', header=None)

In [32]:
market.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
transactions = []
col = set()
for i in range(0, 7501):
    t = []
    for j in range(0, 20):     
        t.append(str(market.values[i,j]))
        col.add(str(market.values[i,j]))
    transactions.append(t)

In [34]:
col.remove('nan')

In [38]:
len(col)

120

In [46]:
transaction_f = []
col = list(col)
for i in range(len(transactions)):
    d = [0]*len(col)
    for j in range(len(transactions[i])):
        item = transactions[i][j]
        if item in col:
            d[col.index(item)] = 1
    transaction_f.append(d)

In [49]:
data = pd.DataFrame(transaction_f, columns=list(col))

In [50]:
data

,mushroom cream sauce,meatballs,whole weat flour,brownies,mint green tea,asparagus,frozen vegetables,olive oil,magazines,melons,...,extra dark chocolate,black tea,champagne,tea,protein bar,chocolate bread,tomato sauce,frozen smoothie,oil,corn
0,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [51]:
data.to_csv("Market_Basket1.csv")

In [54]:
# 挖掘频繁项集，最小支持度为0.02
itemsets = apriori(data, use_colnames=True, min_support=0.003)
# 按照支持度从大到小进行时候粗
itemsets = itemsets.sort_values(by="support" , ascending=False) 
print('-'*20, '频繁项集', '-'*20)
print(itemsets)
# 根据频繁项集计算关联规则，设置最小提升度为2
rules =  association_rules(itemsets, metric='lift', min_threshold=3)
# 按照提升度从大到小进行排序
rules = rules.sort_values(by="lift" , ascending=False) 
#rules.to_csv('./rules.csv')
print('-'*20, '关联规则', '-'*20)
print(rules)

-------------------- 频繁项集 --------------------
       support                                           itemsets
90    0.238368                                    (mineral water)
48    0.179709                                             (eggs)
91    0.174110                                        (spaghetti)
84    0.170911                                     (french fries)
22    0.163845                                        (chocolate)
...        ...                                                ...
1352  0.003066          (spaghetti, herb & pepper, grated cheese)
992   0.003066               (chocolate, french fries, olive oil)
1007  0.003066                       (cake, spaghetti, olive oil)
1017  0.003066                          (chicken, pancakes, milk)
1442  0.003066  (tomatoes, ground beef, spaghetti, mineral water)

[1443 rows x 2 columns]
-------------------- 关联规则 --------------------
                                      antecedents  \
334                     (frozen vegetables, soup)
339                         (milk, mineral water)
234                (frozen vegetables, olive oil)
237                         (milk, mineral water)
149            (whole wheat pasta, mineral water)
..                                            ...
265                         (milk, mineral water)
26                          (shrimp, ground beef)
27                                    (spaghetti)
355                                   (spaghetti)
344  (frozen vegetables, tomatoes, mineral water)

                                      consequents  antecedent support  \
334                         (milk, mineral water)            0.007999
339                     (frozen vegetables, soup)            0.047994
234                         (milk, mineral water)            0.011332
237                (frozen vegetables, olive oil)            0.047994
149                                   (olive oil)            0.009599
..                                            ...                 ...
265                      (chocolate, ground beef)            0.047994
26                                    (spaghetti)            0.011465
27                          (shrimp, ground beef)            0.174110
355  (frozen vegetables, tomatoes, mineral water)            0.174110
344                                   (spaghetti)            0.005866

     consequent support   support  confidence      lift  leverage  conviction
334            0.047994  0.003066    0.383333  7.987176  0.002682    1.543794
339            0.007999  0.003066    0.063889  7.987176  0.002682    1.059704
234            0.047994  0.003333    0.294118  6.128268  0.002789    1.348676
237            0.011332  0.003333    0.069444  6.128268  0.002789    1.062449
149            0.065858  0.003866    0.402778  6.115863  0.003234    1.564145
..                  ...       ...         ...       ...       ...         ...
265            0.023064  0.003333    0.069444  3.010999  0.002226    1.049842
26             0.174110  0.005999    0.523256  3.005315  0.004003    1.732354
27             0.011465  0.005999    0.034456  3.005315  0.004003    1.023812
355            0.005866  0.003066    0.017611  3.002280  0.002045    1.011956
344            0.174110  0.003066    0.522727  3.002280  0.002045    1.730436

[422 rows x 9 columns]